export const SIGN_UP_NEW_CANDIDATE = '@user/SIGN_UP_NEW_CANDIDATE';
export const SIGN_UP_STEP_ONE = '@user/SIGN_UP_STEP_ONE';
export const SIGN_UP_STEP_TWO = '@user/SIGN_UP_STEP_TWO';
export const SIGN_UP_STEP_THREE = '@user/SIGN_UP_STEP_THREE';

export const UPLOAD_AVATAR_REQUEST = '@user/UPLOAD_AVATAR_REQUEST';
export const UPLOAD_AVATAR_SUCCESS = '@user/UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_FAILURE = '@user/UPLOAD_AVATAR_FAILURE';

export const DELETE_AVATAR_REQUEST = '@user/DELETE_AVATAR_REQUEST';
export const DELETE_AVATAR_SUCCESS = '@user/DELETE_AVATAR_SUCCESS';

export const UPLOAD_DOCUMENTS_REQUEST = '@user/UPLOAD_DOCUMENTS_REQUEST';
export const UPLOAD_DOCUMENTS_SUCCESS = '@user/UPLOAD_DOCUMENTS_SUCCESS';
export const UPLOAD_DOCUMENTS_FAILURE = '@user/UPLOAD_DOCUMENTS_FAILURE';
export const DOCUMENTS_UPDATE_PROGRESS = '@user/DOCUMENTS_UPDATE_PROGRESS';

export const DELETE_DOCUMENT_REQUEST = '@user/DELETE_DOCUMENT_REQUEST';
export const DELETE_DOCUMENT_SUCCESS = '@user/DELETE_DOCUMENT_SUCCESS';

export const DELETE_FILES_IN_UNMOUNT_REQUEST =
  '@user/DELETE_FILES_IN_UNMOUNT_REQUEST';
export const DELETE_FILES_IN_UNMOUNT_SUCCESS =
  '@user/DELETE_FILES_IN_UNMOUNT_SUCCESS';
