export const CREATE_NEW_PRODUCT_REQUEST = '@product/CREATE_NEW_PRODUCT_REQUEST';
export const CREATE_NEW_PRODUCT_SUCCESS = '@product/CREATE_NEW_PRODUCT_SUCCESS';
export const CREATE_NEW_PRODUCT_FAILURE = '@product/CREATE_NEW_PRODUCT_FAILURE';
